name: Gerar Test Data

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-test-data:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instalar Node.js
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install

      # 4. Instalar ts-node global para evitar "Permission denied"
      - name: Instalar ts-node global
        run: npm install -g ts-node typescript

      # 5. Rodar update-test-data primeiro (gera/atualiza test-data)
      - name: Rodar update-test-data
        run: npx ts-node .github/scripts/update-foreign-keys.ts

      # 6. Rodar dynamic-tests em seguida
      - name: Rodar dynamic-tests
        run: npx ts-node .github/scripts/run_dynamic_tests.ts

      # 7. Upload somente da pasta test-data
      - name: Upload test-data como artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-data
          path: fontes/backend/test-data
