name: Testes Automáticos PR

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [frontend, backend]
    permissions:
      contents: read
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install
        working-directory: fontes/${{ matrix.test }}

      - name: Instalar jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Atualizar chaves estrangeiras (update-foreign-keys.ts)
        run: |
          npm install -g ts-node typescript
          ts-node fontes/backend/.github/scripts/update-foreign-keys.ts
        working-directory: fontes/backend

      - name: Gerar lista de arquivos alterados
        run: |
          git fetch origin main
          git diff --name-only origin/main HEAD > changed_files.txt
          cat changed_files.txt

      - name: Rodar testes dinâmicos (run_dynamic_tests.sh)
        run: |
          bash fontes/scripts/run_dynamic_tests.sh changed_files.txt ${{ matrix.test }}
        working-directory: fontes

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio_testes_${{ matrix.test }}
          path: relatorio_testes_${{ matrix.test }}.txt

      - name: Upload do test-data
        uses: actions/upload-artifact@v4
        with:
          name: test-data
          path: fontes/backend/test-data

  report-status:
    runs-on: ubuntu-latest
    needs: detect-and-test
    if: always()
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar artifacts frontend
        uses: actions/download-artifact@v4
        with:
          name: relatorio_testes_frontend
          path: ./artifacts/frontend

      - name: Baixar artifacts backend
        uses: actions/download-artifact@v4
        with:
          name: relatorio_testes_backend
          path: ./artifacts/backend

      - name: Baixar artifact test-data
        uses: actions/download-artifact@v4
        with:
          name: test-data
          path: ./artifacts/test-data

      - name: Combinar relatórios
        run: |
          cat ./artifacts/frontend/relatorio_testes_frontend.txt \
              ./artifacts/backend/relatorio_testes_backend.txt > relatorio_testes_completo.txt

      - name: Comentar no PR com o relatório completo
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let report = '';
            try { report = fs.readFileSync('relatorio_testes_completo.txt', 'utf8'); }
            catch (err) { report = 'Relatório de testes não encontrado.'; }

            const commentBody = `### Relatório de Testes\n\n${report}`;
            const prNumber = context.payload.pull_request?.number;

            if (prNumber) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            }
